### ISSUE TITLE
Find a good idea for a project involving rust and a nosql db

### ISSUE THREAD

**Issue by mamaluigie** [mamaluigie/RustDiscordBot#3]
Ideas so far:
---
**Edit the board with ideas**

(Chosen So Far) Discord bot
- Passive Data Sniffer into an organized db based on chat room and create a nosql graph db to display the connections between users chat times. like people who chat with eachother once in a month at least. once in a week at least. we can figure out a way to use the times between posts and the other users that posted at around the same time.

High Level Design
---
- Service will be split up into decoupled microservices that will then be run on containers spun up with kubernetes.
- There will be three main overarching components
1. Discord bot
2. Backend with sql db to keep track of records in real time and nosql graph db which is constantly updated on a cadence of like once per day or hour or something from the mysql db.
3. python machine learning stuff to play with the records in the sql db

**Comment by JarrodCarson** [comment]
I like this. We can determine relationships of when people post messages as well as the most used words per user. It would be interesting.

The important questions is where we will perform this data collection? The Shelby server may be a good place, but what's the  legality of it? If we use that server, we may need to only collect information from users who opt-in. This can be accomplished by supporting a command users can post, and if they post it then that opts them in. We may need to make an announcement of this too.

**Comment by mamaluigie** [comment]
I was thinking that the shelby hall server would be super interesting but was also thinking that it wouldnt be to ethical tho lol.

maybe the announcement thing would be good but I bet that a bunch of people would be weirded out that everything they type is being logged lmao

**Comment by JarrodCarson** [comment]
That's fair. I then propose two things:
- Use a test Discord server
- Develop secondary bot(s) we can use for data generation
